# Generated by nwg-displays on 2025-03-19 at 14:43:06. Do not edit manually.
{ ... }:
{
  wayland.windowManager.hyprland.settings = {
    monitor = [
      "desc:LG Display 0x0521,1920x1080@60.02,4368x2586,1.0"
      "desc:LG Electronics LG ULTRAWIDE 0x000532C6,2560x1080@59.98,1368x1080,1.0"
      "desc:LG Electronics LG ULTRAWIDE 0x000532C6,transform,3"
      "desc:Viewteck Co. Ltd. GFV22CB,1920x1080@60.0,2448x1506,1.0"
    ];
    windowrulev2 = [
      "workspace special:discord, class:^(vesktop)$"
      # Picture-in-Picture rules
      "float, class:(firefox), title:(Picture-in-Picture)"
    ];
    windowrule = [
      "opacity 0.0 override, class:^(xwaylandvideobridge)$"
      "noanim, class:^(xwaylandvideobridge)$"
      "noinitialfocus, class:^(xwaylandvideobridge)$"
      "maxsize 1 1, class:^(xwaylandvideobridge)$"
      "noblur, class:^(xwaylandvideobridge)$"
      "nofocus, class:^(xwaylandvideobridge)$"
    ];
    # NOTE: This may screw with laptop screens, will check later
    workspace = [
      # TODO: Fix monitors to cast to certain displays
    ];

  };
}
